Ændringer fra ekstraordinær generalforsamling 10. April 2021
RusKursusGruppen/vedtaegter pull request #4
Opened 2021-05-29 15:37 UTC by SKroell

2021-06-06 19:58 UTC, BeneCollyridam requested changes
Synes vi skal holde det på maks 80 tegn

2021-06-06 19:58 UTC, BeneCollyridam commented on vedtaegter.tex
> +\item \label{formaal} Foreningens formål er at støtte rusvejlederne i at planlægge og afholde rustur, samt at være til stede under campusdagene. Foreningen har derudover til formål at styrke det soci
Mere end 80 tegn ;) Hold det hellere på flere linjer
```suggestion
\item \label{formaal} Foreningens formål er at støtte rusvejlederne i at
    planlægge og afholde rustur, samt at være til stede under campusdagene.
    Foreningen har derudover til formål at styrke det sociale miljø på DIKU,
    herunder at afholde sociale arrangementer for førsteårsstuderende i løbet
    af studieåret, samt at forbedre studiemiljøet på tværs af alle årgange.
```

2021-06-06 19:58 UTC, BeneCollyridam commented on vedtaegter.tex
> +            \item Bestyrelsen kan se bort for ovenstående og ekstraordinært godkende hyttebumser, skulle der ikke være nok tilmeldte hyttebumser der opfylder ovenstående krav.
```suggestion
            \item Bestyrelsen kan se bort for ovenstående og ekstraordinært
                godkende hyttebumser, skulle der ikke være nok tilmeldte
                hyttebumser der opfylder ovenstående krav.
```

2021-06-06 19:58 UTC, BeneCollyridam commented on vedtaegter.tex
> +    \item Foreningens aktive Facebook-gruppe skal reflektere foreningens medlemmer. Dette inkluderer aktive medlemmer, hyttebumser og eventuelle aspiranter. Tidligere og nuværende medlemmer har mulig
```suggestion
    \item Foreningens aktive Facebook-gruppe skal reflektere foreningens
        medlemmer. Dette inkluderer aktive medlemmer, hyttebumser og eventuelle
        aspiranter. Tidligere og nuværende medlemmer har mulighed for at blive
        en del af en separat alumni Facebook-gruppe.
```

2021-06-06 20:26 UTC, SKroell commented
> Synes vi skal holde det på maks 80 tegn

Havde jeg ikke lige tænkt over. Jeg har tilføjet dine rettelser 👍

2021-06-07 13:26 UTC, BeneCollyridam approved these changes

2022-08-09 15:46 UTC, merged